### ISSUE TITLE
Gradient should extend to bottom of the page

### ISSUE THREAD

**Issue by JenFucci** [ReactNativeNews/react-native-newsletter#18]
The footer should have the same gradient as the rest of the page instead of the solid bg. 

**From this:**
<img width="546" alt="screen shot 2018-01-11 at 5 28 16 pm" src="https://user-images.githubusercontent.com/17892823/34854115-ecdec51c-f6f4-11e7-86af-f5cc40280934.png">

**To this:**
<img width="609" alt="screen shot 2018-01-11 at 5 29 46 pm" src="https://user-images.githubusercontent.com/17892823/34854142-130d70ee-f6f5-11e7-8e49-0c3a8cdff301.png">

**Comment by danielberkompas** [comment]
This has been fixed
