### ISSUE TITLE
Modal does not cover page when page is scrolled

### ISSUE THREAD

**Issue by ajrobertsonio** [ReactNativeNews/react-native-newsletter#20]
After opening the modal, you can scroll down the page:

![2018-01-11_16-39-01](https://user-images.githubusercontent.com/3494509/34854409-67fff826-f6ee-11e7-8be3-8094eb2d92b0.jpg)

Here is the css you need to fix it:

![screen shot 2018-01-11 at 4 41 40 pm](https://user-images.githubusercontent.com/3494509/34854404-5c59ea40-f6ee-11e7-8d66-43f66f81892d.png)

**Comment by ajrobertsonio** [comment]
You may also need to add `overflow: scroll;`. When the validation errors appear it may push the submit button off the screen.

**Comment by danielberkompas** [comment]
Unfortunately it's not quite that simple, because iPhone 6 screens and smaller require the modal to be scrollable, and `overflow: scroll` doesn't work for that, apparently.

I switched to a hybrid system: `position: fixed` on desktop and `position: absolute` on mobile.
