### ISSUE TITLE
'Your email' arrow is not a clickable button

### ISSUE THREAD

**Issue by ajrobertsonio** [ReactNativeNews/react-native-newsletter#21]
I expect the 'Your email' arrow to be clickable. I have to press 'enter' to submit my email address. 

![2018-01-11_16-38-17](https://user-images.githubusercontent.com/3494509/34854467-bc5bbdf6-f6ee-11e7-83d3-8ca1b6e69c06.jpg)

Also, the input + submit combo is not consistent with the input + submit combo found in the modal. The modal includes a red button to submit.

![2018-01-11_16-38-50](https://user-images.githubusercontent.com/3494509/34854472-bf90b382-f6ee-11e7-8baf-66dd5851c9d8.jpg)

**Comment by danielberkompas** [comment]
I made the arrow on the subscribe form clickable. Regarding the inconsistency between the two forms: it was present in the designs, so I assume the design team is okay with it.
