### ISSUE TITLE
Email error text spacing

### ISSUE THREAD

**Issue by ajrobertsonio** [ReactNativeNews/react-native-newsletter#23]
The error message text is not spaced correctly. After entering an invalid email a new tab is opened, but once you return to the previous page, you can see the error message text is cramped. 

![2018-01-11_16-46-09](https://user-images.githubusercontent.com/3494509/34854539-20a15604-f6ef-11e7-8d0c-80f583ff5db1.jpg)

**Comment by JenFucci** [comment]
Should be:
font-family: DroidSerif-Italic;
font-size: 13px;
color: #E73536;
letter-spacing: 0.26px;
line-height: 35px;

<img width="350" alt="screen shot 2018-01-11 at 5 47 33 pm" src="https://user-images.githubusercontent.com/17892823/34854561-9ba592a4-f6f7-11e7-89fd-6a2e2311e610.png">

**Comment by danielberkompas** [comment]
Thanks, this has been fixed!
