### ISSUE TITLE
No RSS for http://reactnative.cc?

### ISSUE THREAD

**Issue by trietbui85** [ReactNativeNews/react-native-newsletter#27]
I would like to subscribe for RSS of http://reactnative.cc but I haven't seen it yet. Could you please please confirm with me whether such RSS link exists? Thanks.

**Comment by alexdevero** [comment]
I would like to know this as well. RSS support would be great.

**Comment by fvonhoven** [comment]
Give this a try: https://us10.campaign-archive.com/feed?u=db0dd948e2b729ee62625b1a8&id=47cd41008f

**Comment by trietbui85** [comment]
Thanks, that link works great. I'm able to import it to Feedly now.
