### ISSUE TITLE
Limit to 1 column?

### ISSUE THREAD

**Issue by martnu** [ReactNativeNews/react-native-newsletter#8]
The articles are quite dense and not really readable on mobile. What about limiting to one column layout?
![img_2939](https://cloud.githubusercontent.com/assets/186496/12318809/7da9d58c-ba9d-11e5-941e-953c81da3bcb.PNG)

**Comment by brentvatne** [comment]
@martnu - indeed this template is awful on Gmail :( I use the built in one with [Goodbits](https://goodbits.io) -- it's supposed to limit to one column but breaks on Gmail (of all clients to break on..)

cc @garbles @pcreux
